/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;
import controlador.Controlador;
import modelo.*;
import java.util.Scanner;


/**
 *
 * @author Admin
 */
public class InterfazGrafica extends javax.swing.JFrame {
    private Piloto pilotoSeleccionado = null;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
        panelContenedor.removeAll();
        panelContenedor.add(panelInicio);
        panelContenedor.repaint();
        panelContenedor.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRolPiloto = new javax.swing.ButtonGroup();
        grupoLicenciaFIAModificar = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();
        botonPilotos = new javax.swing.JButton();
        botonComisarios = new javax.swing.JButton();
        botonEquipos = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelCargarPiloto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoNombrePiloto = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoApellidoPiloto = new javax.swing.JTextPane();
        campoNacionalidadPiloto = new javax.swing.JComboBox<>();
        campoNroAutoPiloto = new javax.swing.JTextField();
        campoEquipoPiloto = new javax.swing.JComboBox<>();
        pTitular = new javax.swing.JRadioButton();
        pProbador = new javax.swing.JRadioButton();
        pReserva = new javax.swing.JRadioButton();
        botonGuardarPiloto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        campoDiaPiloto = new javax.swing.JTextField();
        campoMesPiloto = new javax.swing.JTextField();
        campoAnoPiloto = new javax.swing.JTextField();
        campoPuntosPiloto = new javax.swing.JTextField();
        campoPodiosPiloto = new javax.swing.JTextField();
        campoPolesPiloto = new javax.swing.JTextField();
        campoVueltasRapidasPiloto = new javax.swing.JTextField();
        campoPenalizacionesPiloto = new javax.swing.JTextField();
        campoAbandonosPiloto = new javax.swing.JTextField();
        checkFIATruePiloto = new javax.swing.JRadioButton();
        checkFIAFalsePiloto = new javax.swing.JRadioButton();
        panelComisarios = new javax.swing.JPanel();
        botonCargarComisario = new javax.swing.JButton();
        botonEliminarComisario = new javax.swing.JButton();
        botonMostrarComisario = new javax.swing.JButton();
        panelModificarPiloto = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        campoIDModPiloto = new javax.swing.JTextField();
        botonBuscarPilotoAModificar = new javax.swing.JButton();
        panelEquipos = new javax.swing.JPanel();
        botonMostrarEquipos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelPilotos = new javax.swing.JPanel();
        botonCargarPiloto = new javax.swing.JButton();
        botonEliminarPiloto = new javax.swing.JButton();
        botonMostrarPilotos = new javax.swing.JButton();
        botonModificarPiloto = new javax.swing.JButton();
        panelCamposModificarPiloto = new javax.swing.JPanel();
        campoNroAutoModificar = new javax.swing.JTextField();
        campoPuntosModificar = new javax.swing.JTextField();
        botonCancelarPilotoModificado = new javax.swing.JButton();
        labelPilotoEncontrado = new javax.swing.JLabel();
        campoPodiosModificar = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        campoPolesModificar = new javax.swing.JTextField();
        campoVueltasRapidasModificar = new javax.swing.JTextField();
        campoAbandonosModificar = new javax.swing.JTextField();
        campoPenalizacionesModificar = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        checkFIATrue = new javax.swing.JRadioButton();
        checkFIAFalse = new javax.swing.JRadioButton();
        pTitularModificar = new javax.swing.JRadioButton();
        pReservaModificar = new javax.swing.JRadioButton();
        pProbadorModificar = new javax.swing.JRadioButton();
        botonGuardarPilotoModificado = new javax.swing.JButton();
        panelMostrarPilotos = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1020, 560));
        setMinimumSize(new java.awt.Dimension(1020, 560));
        setPreferredSize(new java.awt.Dimension(640, 360));
        setSize(new java.awt.Dimension(1020, 560));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("F1 Manager 2025 v0.0.1 Magios Inc. 2025");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\GitHub\\PMI-F1-2025\\PMI-Prog2\\src\\main\\java\\Imagenes\\F1.png")); // NOI18N
        jLabel1.setText("Manager 2025");

        panelBotones.setBackground(new java.awt.Color(51, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        botonInicio.setText("Inicio");
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });

        botonPilotos.setText("Pilotos");
        botonPilotos.setMaximumSize(new java.awt.Dimension(93, 27));
        botonPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPilotosActionPerformed(evt);
            }
        });

        botonComisarios.setText("Comisarios");
        botonComisarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComisariosActionPerformed(evt);
            }
        });

        botonEquipos.setText("Equipos");
        botonEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonPilotos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonComisarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(botonEquipos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(botonPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(botonComisarios, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(botonEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelContenedor.setMaximumSize(new java.awt.Dimension(640, 360));
        panelContenedor.setPreferredSize(new java.awt.Dimension(1280, 720));

        panelInicio.setMaximumSize(new java.awt.Dimension(720, 1280));
        panelInicio.setLayout(new java.awt.CardLayout());
        panelInicio.add(jLabel3, "card2");

        panelCargarPiloto.setBackground(new java.awt.Color(102, 102, 102));
        panelCargarPiloto.setForeground(new java.awt.Color(153, 255, 255));
        panelCargarPiloto.setMaximumSize(null);
        panelCargarPiloto.setOpaque(false);

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Cargar Piloto");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre:");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Apellido:");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nacionalidad:");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Fecha de nacimiento:");

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Numero de auto:");

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Equipo actual:");

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Rol en el equipo:");

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Puntos:");

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Podios:");

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Poles:");

        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Vueltas rapidas:");

        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Penalizaciones:");

        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Abandonos (DNF):");

        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Licencia FIA:");

        jScrollPane1.setViewportView(campoNombrePiloto);

        jScrollPane3.setViewportView(campoApellidoPiloto);

        campoNacionalidadPiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Chile", "Alemania", "Suecia", "Arabia Saudi", "Gran Bretaña", "Bolivia", "Brasil", "Uruguay", "Perú", "México", "Francia" }));
        campoNacionalidadPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNacionalidadPilotoActionPerformed(evt);
            }
        });

        campoNroAutoPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNroAutoPilotoActionPerformed(evt);
            }
        });

        campoEquipoPiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ferrari", "Red Bull Racing", "McLaren", "Haas", "Los Na", "Alpine", "Racing Bulls", "Williams", "Aston Martin", "Magios Racing" }));

        grupoRolPiloto.add(pTitular);
        pTitular.setForeground(new java.awt.Color(51, 51, 51));
        pTitular.setText("Titular");
        pTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTitularActionPerformed(evt);
            }
        });

        grupoRolPiloto.add(pProbador);
        pProbador.setForeground(new java.awt.Color(51, 51, 51));
        pProbador.setText("Probador");
        pProbador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pProbadorActionPerformed(evt);
            }
        });

        grupoRolPiloto.add(pReserva);
        pReserva.setForeground(new java.awt.Color(51, 51, 51));
        pReserva.setText("Reserva");
        pReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pReservaActionPerformed(evt);
            }
        });

        botonGuardarPiloto.setText("Guardar");
        botonGuardarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPilotoActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("dia: ");
        jLabel19.setToolTipText("");

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("mes:");
        jLabel20.setToolTipText("");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("año:");
        jLabel21.setToolTipText("");

        campoDiaPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiaPilotoActionPerformed(evt);
            }
        });

        grupoLicenciaFIAModificar.add(checkFIATruePiloto);
        checkFIATruePiloto.setForeground(new java.awt.Color(51, 51, 51));
        checkFIATruePiloto.setText("Si");

        grupoLicenciaFIAModificar.add(checkFIAFalsePiloto);
        checkFIAFalsePiloto.setForeground(new java.awt.Color(51, 51, 51));
        checkFIAFalsePiloto.setText("No");

        javax.swing.GroupLayout panelCargarPilotoLayout = new javax.swing.GroupLayout(panelCargarPiloto);
        panelCargarPiloto.setLayout(panelCargarPilotoLayout);
        panelCargarPilotoLayout.setHorizontalGroup(
            panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargarPilotoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonGuardarPiloto)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCargarPilotoLayout.createSequentialGroup()
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pProbador)
                                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                                .addComponent(pTitular)
                                                .addGap(190, 190, 190)
                                                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel18)))
                                            .addComponent(pReserva))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                                .addGap(0, 107, Short.MAX_VALUE)
                                                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(campoPuntosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(campoPodiosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(campoPolesPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(campoVueltasRapidasPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(campoPenalizacionesPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(campoAbandonosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(checkFIAFalsePiloto)
                                            .addComponent(checkFIATruePiloto)))))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNroAutoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoDiaPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoMesPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAnoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(campoNacionalidadPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoEquipoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        panelCargarPilotoLayout.setVerticalGroup(
            panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(37, 37, 37)
                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(campoNacionalidadPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(campoDiaPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoMesPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoAnoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(campoNroAutoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(campoEquipoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(pTitular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pReserva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pProbador))
                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(campoPuntosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(campoPodiosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(campoPolesPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(campoVueltasRapidasPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(campoPenalizacionesPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(campoAbandonosPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(checkFIATruePiloto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkFIAFalsePiloto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonGuardarPiloto)
                .addContainerGap())
        );

        botonCargarComisario.setText("Cargar comisario");
        botonCargarComisario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarComisarioActionPerformed(evt);
            }
        });

        botonEliminarComisario.setText("Eliminar Comisario");
        botonEliminarComisario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarComisarioActionPerformed(evt);
            }
        });

        botonMostrarComisario.setText("Mostrar comisarios");
        botonMostrarComisario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarComisarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelComisariosLayout = new javax.swing.GroupLayout(panelComisarios);
        panelComisarios.setLayout(panelComisariosLayout);
        panelComisariosLayout.setHorizontalGroup(
            panelComisariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComisariosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelComisariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonMostrarComisario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarComisario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCargarComisario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panelComisariosLayout.setVerticalGroup(
            panelComisariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComisariosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(botonCargarComisario)
                .addGap(18, 18, 18)
                .addComponent(botonEliminarComisario)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarComisario)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Modificar Piloto");

        jLabel23.setText("Ingrese el identificador (ID) del piloto a modificar:");

        campoIDModPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDModPilotoActionPerformed(evt);
            }
        });

        botonBuscarPilotoAModificar.setText("Buscar");
        botonBuscarPilotoAModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPilotoAModificarActionPerformed(evt);
            }
        });

        panelEquipos.setMaximumSize(new java.awt.Dimension(780, 494));

        botonMostrarEquipos.setText("Mostrar Equipos");
        botonMostrarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarEquiposActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nro de Auto", "Equipo", "Rol", "Podios", "Penalizaciones", "Poles", "Licencia FIA", "Vueltas Rapidas"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout panelEquiposLayout = new javax.swing.GroupLayout(panelEquipos);
        panelEquipos.setLayout(panelEquiposLayout);
        panelEquiposLayout.setHorizontalGroup(
            panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquiposLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(botonMostrarEquipos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(625, 625, 625))
        );
        panelEquiposLayout.setVerticalGroup(
            panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquiposLayout.createSequentialGroup()
                .addGroup(panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEquiposLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                    .addGroup(panelEquiposLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(botonMostrarEquipos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        botonCargarPiloto.setText("Cargar piloto");
        botonCargarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarPilotoActionPerformed(evt);
            }
        });

        botonEliminarPiloto.setText("Eliminar piloto");
        botonEliminarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPilotoActionPerformed(evt);
            }
        });

        botonMostrarPilotos.setText("Mostrar pilotos");
        botonMostrarPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarPilotosActionPerformed(evt);
            }
        });

        botonModificarPiloto.setText("Modificar piloto");
        botonModificarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPilotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPilotosLayout = new javax.swing.GroupLayout(panelPilotos);
        panelPilotos.setLayout(panelPilotosLayout);
        panelPilotosLayout.setHorizontalGroup(
            panelPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilotosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonMostrarPilotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCargarPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(363, Short.MAX_VALUE))
        );
        panelPilotosLayout.setVerticalGroup(
            panelPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilotosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(botonCargarPiloto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonModificarPiloto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonEliminarPiloto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonMostrarPilotos)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelModificarPilotoLayout = new javax.swing.GroupLayout(panelModificarPiloto);
        panelModificarPiloto.setLayout(panelModificarPilotoLayout);
        panelModificarPilotoLayout.setHorizontalGroup(
            panelModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarPilotoLayout.createSequentialGroup()
                .addGroup(panelModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarPilotoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModificarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoIDModPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBuscarPilotoAModificar))
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModificarPilotoLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(panelPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(585, Short.MAX_VALUE))
        );
        panelModificarPilotoLayout.setVerticalGroup(
            panelModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarPilotoLayout.createSequentialGroup()
                .addComponent(panelPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModificarPilotoLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(campoIDModPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscarPilotoAModificar)))
                    .addComponent(panelEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCamposModificarPiloto.setBackground(new java.awt.Color(204, 255, 255));
        panelCamposModificarPiloto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelCamposModificarPiloto.setForeground(new java.awt.Color(0, 204, 204));

        botonCancelarPilotoModificado.setText("Cancelar");
        botonCancelarPilotoModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarPilotoModificadoActionPerformed(evt);
            }
        });

        labelPilotoEncontrado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPilotoEncontrado.setForeground(new java.awt.Color(51, 51, 51));

        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Numero de Auto:");

        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Rol:");

        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Puntos:");

        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Podios:");

        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Poles:");

        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Vueltas Rápidas:");

        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Penalizaciones:");

        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Abandonos (DNF):");

        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Licencia FIA:");

        grupoLicenciaFIAModificar.add(checkFIATrue);
        checkFIATrue.setForeground(new java.awt.Color(51, 51, 51));
        checkFIATrue.setText("Si");
        checkFIATrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFIATrueActionPerformed(evt);
            }
        });

        grupoLicenciaFIAModificar.add(checkFIAFalse);
        checkFIAFalse.setForeground(new java.awt.Color(51, 51, 51));
        checkFIAFalse.setText("No");
        checkFIAFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFIAFalseActionPerformed(evt);
            }
        });

        grupoRolPiloto.add(pTitularModificar);
        pTitularModificar.setForeground(new java.awt.Color(51, 51, 51));
        pTitularModificar.setText("Titular");

        grupoRolPiloto.add(pReservaModificar);
        pReservaModificar.setForeground(new java.awt.Color(51, 51, 51));
        pReservaModificar.setText("Reserva");
        pReservaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pReservaModificarActionPerformed(evt);
            }
        });

        grupoRolPiloto.add(pProbadorModificar);
        pProbadorModificar.setForeground(new java.awt.Color(51, 51, 51));
        pProbadorModificar.setText("Probador");

        botonGuardarPilotoModificado.setText("Guardar Cambios");
        botonGuardarPilotoModificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPilotoModificadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCamposModificarPilotoLayout = new javax.swing.GroupLayout(panelCamposModificarPiloto);
        panelCamposModificarPiloto.setLayout(panelCamposModificarPilotoLayout);
        panelCamposModificarPilotoLayout.setHorizontalGroup(
            panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCamposModificarPilotoLayout.createSequentialGroup()
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pReservaModificar)
                                    .addComponent(pTitularModificar)
                                    .addComponent(pProbadorModificar)))
                            .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNroAutoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91)
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoVueltasRapidasModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(campoPenalizacionesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoAbandonosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                                        .addComponent(checkFIATrue)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkFIAFalse)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCamposModificarPilotoLayout.createSequentialGroup()
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPilotoEncontrado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCamposModificarPilotoLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(campoPodiosModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(campoPolesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoPuntosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCamposModificarPilotoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCancelarPilotoModificado)
                .addGap(18, 18, 18)
                .addComponent(botonGuardarPilotoModificado)
                .addContainerGap())
        );
        panelCamposModificarPilotoLayout.setVerticalGroup(
            panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                .addComponent(labelPilotoEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNroAutoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(pTitularModificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pReservaModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pProbadorModificar)
                        .addGap(8, 8, 8)
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(campoPuntosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(campoPodiosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(campoPolesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCamposModificarPilotoLayout.createSequentialGroup()
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoVueltasRapidasModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoPenalizacionesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(campoAbandonosModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(checkFIATrue)
                            .addComponent(checkFIAFalse))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCamposModificarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelarPilotoModificado)
                    .addComponent(botonGuardarPilotoModificado))
                .addContainerGap())
        );

        jLabel32.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Pilotos");

        javax.swing.GroupLayout panelMostrarPilotosLayout = new javax.swing.GroupLayout(panelMostrarPilotos);
        panelMostrarPilotos.setLayout(panelMostrarPilotosLayout);
        panelMostrarPilotosLayout.setHorizontalGroup(
            panelMostrarPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarPilotosLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel32)
                .addContainerGap(121, Short.MAX_VALUE))
        );
        panelMostrarPilotosLayout.setVerticalGroup(
            panelMostrarPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMostrarPilotosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel32)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(panelMostrarPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(panelComisarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(panelCamposModificarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1397, Short.MAX_VALUE)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(664, 664, 664)
                    .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(665, 665, 665)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(644, 644, 644)
                    .addComponent(panelCargarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(644, Short.MAX_VALUE)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelModificarPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMostrarPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(panelComisarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(984, Short.MAX_VALUE)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(panelCamposModificarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(687, Short.MAX_VALUE)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(609, 609, 609)
                    .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(402, 402, 402)
                    .addComponent(panelCargarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(403, Short.MAX_VALUE)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelModificarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                                .addComponent(jLabel2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 121, Short.MAX_VALUE)
                        .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCargarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarPilotoActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelCargarPiloto);
        panelContenedor.repaint();
        panelContenedor.revalidate();        
    }//GEN-LAST:event_botonCargarPilotoActionPerformed

    private void botonEliminarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarPilotoActionPerformed

    private void botonMostrarPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarPilotosActionPerformed
        // TODO add your handling code here:
        //para control
        if(Controlador.getListaPilotos() == null) System.out.println("no se pudo cargar los pilotos");
        else{
            Controlador.getListaPilotos().mostrarTodosLosPilotos();
        }
        
        panelContenedor.removeAll();
        panelContenedor.add(panelMostrarPilotos);
        panelContenedor.repaint();
        panelContenedor.revalidate();
        
        
    }//GEN-LAST:event_botonMostrarPilotosActionPerformed

    private void botonCargarComisarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarComisarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCargarComisarioActionPerformed

    private void botonEliminarComisarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarComisarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarComisarioActionPerformed

    private void botonMostrarComisarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarComisarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMostrarComisarioActionPerformed

    private void botonMostrarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMostrarEquiposActionPerformed

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelInicio);
        panelContenedor.repaint();
        panelContenedor.revalidate();
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPilotosActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelPilotos);
        panelContenedor.repaint();
        panelContenedor.revalidate();
    }//GEN-LAST:event_botonPilotosActionPerformed

    private void botonComisariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComisariosActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelComisarios);
        panelContenedor.repaint();
        panelContenedor.revalidate();        
    }//GEN-LAST:event_botonComisariosActionPerformed

    private void botonEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEquiposActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelEquipos);
        panelContenedor.repaint();
        panelContenedor.revalidate();        
    }//GEN-LAST:event_botonEquiposActionPerformed

    private void campoNacionalidadPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNacionalidadPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNacionalidadPilotoActionPerformed

    private void campoNroAutoPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNroAutoPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNroAutoPilotoActionPerformed

    private void botonGuardarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPilotoActionPerformed
        // TODO add your handling code here:
        grupoRolPiloto.add(pTitular);
        grupoRolPiloto.add(pReserva);
        grupoRolPiloto.add(pProbador);
        Piloto p = new Piloto();
        p.setNombre(campoNombrePiloto.getText());
        p.setApellido(campoApellidoPiloto.getText());
        Fecha fechaNac = new Fecha();
        fechaNac.setDia(Integer.parseInt(campoDiaPiloto.getText()));
        fechaNac.setMes(Integer.parseInt(campoMesPiloto.getText()));
        fechaNac.setAno(Integer.parseInt(campoAnoPiloto.getText()));
        p.setFechaDeNacimiento(fechaNac);
        p.setNumeroDeAuto(Integer.parseInt(campoNroAutoPiloto.getText()));
        p.setEquipo(campoEquipoPiloto.getSelectedItem().toString());
        p.setNacionalidad(campoNacionalidadPiloto.getSelectedItem().toString());String rol = "";
        if(pTitular.isSelected()) rol = "Titular";
        else if(pReserva.isSelected()) rol = "Reserva";
        else if(pProbador.isSelected()) rol = "Probador";
        p.setRol(rol);
        p.setPuntos(Integer.parseInt(campoPuntosPiloto.getText()));
        p.setPodios(Integer.parseInt(campoPodiosPiloto.getText()));
        p.setPoles(Integer.parseInt(campoPolesPiloto.getText()));
        p.setVueltasRapidas(Integer.parseInt(campoVueltasRapidasPiloto.getText()));
        p.setPenalizaciones(Integer.parseInt(campoPenalizacionesPiloto.getText()));
        p.setAbandonos(Integer.parseInt(campoAbandonosPiloto.getText()));
        p.setFia(checkFIATruePiloto.isSelected());
        if(Controlador.agregarPilotoInterfaz(p)){
            JOptionPane.showMessageDialog(this, "Se cargó el piloto correctamente\nID: " + p.getID(), "Carga Exitosa", JOptionPane.INFORMATION_MESSAGE);
            Controlador.actualizarArchivo();
        }else JOptionPane.showMessageDialog(this, "Error: No se pudo cargar el piloto (repetido)", "Error", JOptionPane.ERROR_MESSAGE);
        
        
    }//GEN-LAST:event_botonGuardarPilotoActionPerformed

    private void pProbadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pProbadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pProbadorActionPerformed

    private void pReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pReservaActionPerformed

    private void pTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pTitularActionPerformed

    private void campoDiaPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiaPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDiaPilotoActionPerformed

    private void botonModificarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPilotoActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelModificarPiloto);
        panelContenedor.repaint();
        panelContenedor.revalidate();    
    }//GEN-LAST:event_botonModificarPilotoActionPerformed

    private void campoIDModPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDModPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDModPilotoActionPerformed

    private void botonBuscarPilotoAModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPilotoAModificarActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(campoIDModPiloto.getText());
            Piloto original = Controlador.getListaPilotos().buscarPilotoPorID(id);
            if (original != null) {
                Piloto p = new Piloto(
                        original.getID(),
                        original.getNombre(),
                        original.getApellido(),
                        original.getFechaDeNacimiento(),
                        original.getNacionalidad(),
                        original.getNumeroDeAuto(),
                        original.getEquipo(),
                        original.getRol(),
                        original.getPuntos(),
                        original.getPodios(),
                        original.getPoles(),
                        original.getVueltasRapidas(),
                        original.getPenalizaciones(),
                        original.getAbandonos(),
                        original.getFia()
                );
                // Si lo encontró:
                labelPilotoEncontrado.setText("Piloto encontrado: "+ p.getNombre() + " " + p.getApellido());
                campoNroAutoModificar.setText(String.valueOf(p.getNumeroDeAuto()));
                if(p.getRol().equals("Titular")) pTitularModificar.setSelected(true);
                if(p.getRol().equals("Probador")) pProbadorModificar.setSelected(true);
                if(p.getRol().equals("Reserva")) pReservaModificar.setSelected(true);
                campoPuntosModificar.setText(String.valueOf(p.getPuntos()));
                campoPodiosModificar.setText(String.valueOf(p.getPodios()));
                campoPolesModificar.setText(String.valueOf(p.getPoles()));
                campoVueltasRapidasModificar.setText(String.valueOf(p.getVueltasRapidas()));
                campoPenalizacionesModificar.setText(String.valueOf(p.getPenalizaciones()));
                campoAbandonosModificar.setText(String.valueOf(p.getAbandonos()));
                if(p.getFia()) checkFIATrue.setSelected(true);
                checkFIAFalse.setSelected(true);
                pilotoSeleccionado = p;
                // Mostramos el panel de edición
                panelContenedor.removeAll();
                panelContenedor.add(panelCamposModificarPiloto);
                panelContenedor.repaint();
                panelContenedor.revalidate();
            } else {
                // Si no lo encontró:
                JOptionPane.showMessageDialog(this, 
                    "No se encontró ningún piloto con ID " + id, 
                    "Piloto no encontrado", 
                    JOptionPane.WARNING_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
            "Debe ingresar un número de auto válido.", 
            "Error de formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonBuscarPilotoAModificarActionPerformed

    private void checkFIATrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFIATrueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFIATrueActionPerformed

    private void checkFIAFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFIAFalseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFIAFalseActionPerformed

    private void pReservaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pReservaModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pReservaModificarActionPerformed

    private void botonGuardarPilotoModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPilotoModificadoActionPerformed
        // TODO add your handling code here:
        if(pilotoSeleccionado == null){
            JOptionPane.showMessageDialog(this, "No hay ningún piloto seleccionado",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        Piloto p = pilotoSeleccionado;
        //----- modificar los parametros de p -----
        p.setNumeroDeAuto(Integer.parseInt(campoNroAutoModificar.getText()));
        p.setPuntos(Integer.parseInt(campoPuntosModificar.getText()));
        p.setPodios(Integer.parseInt(campoPodiosModificar.getText()));
        p.setPoles(Integer.parseInt(campoPolesModificar.getText()));
        p.setVueltasRapidas(Integer.parseInt(campoVueltasRapidasModificar.getText()));
        p.setPenalizaciones(Integer.parseInt(campoPenalizacionesModificar.getText()));
        p.setAbandonos(Integer.parseInt(campoAbandonosModificar.getText()));
        if(pTitularModificar.isSelected()) p.setRol("Titular");
        else if(pReservaModificar.isSelected()) p.setRol("Reserva");
        else p.setRol("Probador");
        if(checkFIATrue.isSelected()) p.setFia(true);
        else p.setFia(false);
        if(Controlador.modificarPilotoInterfaz(p)){
            JOptionPane.showMessageDialog(this, "Se modificó el piloto correctamente", "Modificación Exitosa", JOptionPane.INFORMATION_MESSAGE);
            Controlador.actualizarArchivo();
        }else JOptionPane.showMessageDialog(this, "No se pudo modificar el piloto", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botonGuardarPilotoModificadoActionPerformed

    private void botonCancelarPilotoModificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarPilotoModificadoActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelModificarPiloto);
        panelContenedor.repaint();
        panelContenedor.revalidate();  
        
    }//GEN-LAST:event_botonCancelarPilotoModificadoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarPilotoAModificar;
    private javax.swing.JButton botonCancelarPilotoModificado;
    private javax.swing.JButton botonCargarComisario;
    private javax.swing.JButton botonCargarPiloto;
    private javax.swing.JButton botonComisarios;
    private javax.swing.JButton botonEliminarComisario;
    private javax.swing.JButton botonEliminarPiloto;
    private javax.swing.JButton botonEquipos;
    private javax.swing.JButton botonGuardarPiloto;
    private javax.swing.JButton botonGuardarPilotoModificado;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonModificarPiloto;
    private javax.swing.JButton botonMostrarComisario;
    private javax.swing.JButton botonMostrarEquipos;
    private javax.swing.JButton botonMostrarPilotos;
    private javax.swing.JButton botonPilotos;
    private javax.swing.JTextField campoAbandonosModificar;
    private javax.swing.JTextField campoAbandonosPiloto;
    private javax.swing.JTextField campoAnoPiloto;
    private javax.swing.JTextPane campoApellidoPiloto;
    private javax.swing.JTextField campoDiaPiloto;
    private javax.swing.JComboBox<String> campoEquipoPiloto;
    private javax.swing.JTextField campoIDModPiloto;
    private javax.swing.JTextField campoMesPiloto;
    private javax.swing.JComboBox<String> campoNacionalidadPiloto;
    private javax.swing.JTextPane campoNombrePiloto;
    private javax.swing.JTextField campoNroAutoModificar;
    private javax.swing.JTextField campoNroAutoPiloto;
    private javax.swing.JTextField campoPenalizacionesModificar;
    private javax.swing.JTextField campoPenalizacionesPiloto;
    private javax.swing.JTextField campoPodiosModificar;
    private javax.swing.JTextField campoPodiosPiloto;
    private javax.swing.JTextField campoPolesModificar;
    private javax.swing.JTextField campoPolesPiloto;
    private javax.swing.JTextField campoPuntosModificar;
    private javax.swing.JTextField campoPuntosPiloto;
    private javax.swing.JTextField campoVueltasRapidasModificar;
    private javax.swing.JTextField campoVueltasRapidasPiloto;
    private javax.swing.JRadioButton checkFIAFalse;
    private javax.swing.JRadioButton checkFIAFalsePiloto;
    private javax.swing.JRadioButton checkFIATrue;
    private javax.swing.JRadioButton checkFIATruePiloto;
    private javax.swing.ButtonGroup grupoLicenciaFIAModificar;
    private javax.swing.ButtonGroup grupoRolPiloto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelPilotoEncontrado;
    private javax.swing.JRadioButton pProbador;
    private javax.swing.JRadioButton pProbadorModificar;
    private javax.swing.JRadioButton pReserva;
    private javax.swing.JRadioButton pReservaModificar;
    private javax.swing.JRadioButton pTitular;
    private javax.swing.JRadioButton pTitularModificar;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCamposModificarPiloto;
    private javax.swing.JPanel panelCargarPiloto;
    private javax.swing.JPanel panelComisarios;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelEquipos;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelModificarPiloto;
    private javax.swing.JPanel panelMostrarPilotos;
    private javax.swing.JPanel panelPilotos;
    // End of variables declaration//GEN-END:variables
}