/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.ComisarioDeportivo;
import modelo.Equipo;
import modelo.ListaEquipos;
import modelo.Fecha;
import modelo.ListaPilotos;
import modelo.ManejoArchivos;
import modelo.Piloto;

/**
 *
 * @author Admin
 */
public class InterfazGrafica extends javax.swing.JFrame {
    private ListaPilotos lista = new ListaPilotos();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGrafica.class.getName());

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRolPiloto = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonPilotos = new javax.swing.JButton();
        botonComisarios = new javax.swing.JButton();
        botonEquipos = new javax.swing.JButton();
        panelContenedor = new javax.swing.JPanel();
        panelCargarPiloto = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoNombrePiloto = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        campoApellidoPiloto = new javax.swing.JTextPane();
        campoNacionalidadPiloto = new javax.swing.JComboBox<>();
        campoNroAutoPiloto = new javax.swing.JTextField();
        campoEquipoPiloto = new javax.swing.JComboBox<>();
        botonGuardarPiloto = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        campoDiaPiloto = new javax.swing.JTextField();
        campoMesPiloto = new javax.swing.JTextField();
        campoAnoPiloto = new javax.swing.JTextField();
        pReserva = new javax.swing.JRadioButton();
        pTitular = new javax.swing.JRadioButton();
        pProbador = new javax.swing.JRadioButton();
        panelInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelPilotos = new javax.swing.JPanel();
        botonCargarPiloto = new javax.swing.JButton();
        botonEliminarPiloto = new javax.swing.JButton();
        botonMostrarPilotos = new javax.swing.JButton();
        panelComisarios = new javax.swing.JPanel();
        botonCargarComisario = new javax.swing.JButton();
        botonEliminarComisario = new javax.swing.JButton();
        botonMostrarComisario = new javax.swing.JButton();
        panelEquipos = new javax.swing.JPanel();
        botonMostrarEquipos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("F1 Manager 2025 v0.0.0 Magios Inc. 2025");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("F1 Manager 2025");

        panelBotones.setBackground(new java.awt.Color(40, 40, 40));

        botonPilotos.setText("Pilotos");
        botonPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPilotosActionPerformed(evt);
            }
        });

        botonComisarios.setText("Comisarios");
        botonComisarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComisariosActionPerformed(evt);
            }
        });

        botonEquipos.setText("Equipos");
        botonEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(botonPilotos)
                .addGap(31, 31, 31)
                .addComponent(botonComisarios)
                .addGap(26, 26, 26)
                .addComponent(botonEquipos)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPilotos)
                    .addComponent(botonComisarios)
                    .addComponent(botonEquipos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCargarPiloto.setBackground(new java.awt.Color(102, 102, 102));
        panelCargarPiloto.setForeground(new java.awt.Color(153, 255, 255));
        panelCargarPiloto.setOpaque(false);

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Cargar Piloto");

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre:");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Apellido:");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Nacionalidad:");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Fecha de nacimiento:");

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Numero de auto:");

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Equipo actual:");

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Rol en el equipo:");

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Puntos:");

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Podios:");

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Poles:");

        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Vueltas rapidas:");

        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Penalizaciones:");

        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Abandonos (DNF):");

        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Licencia FIA:");

        jScrollPane1.setViewportView(campoNombrePiloto);

        jScrollPane3.setViewportView(campoApellidoPiloto);

        campoNacionalidadPiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentino", "Chileno", "Aleman", "Sueco", "Arabe", "Ingles", "Boliviano", "Brasileño", "Uruguayo", "Peruano", "Mexicano" }));
        campoNacionalidadPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNacionalidadPilotoActionPerformed(evt);
            }
        });

        campoNroAutoPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNroAutoPilotoActionPerformed(evt);
            }
        });

        campoEquipoPiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Losco F1", "Glep Racing", "McLaren", "Miskatonic Race", "Los Nazis", "Fiumba", "Nashe", "Full Races", "Tito Calderón", "Magios Racists" }));

        botonGuardarPiloto.setText("Guardar");
        botonGuardarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPilotoActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("dia:");

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("mes:");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("año:");

        campoDiaPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDiaPilotoActionPerformed(evt);
            }
        });

        campoMesPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMesPilotoActionPerformed(evt);
            }
        });

        campoAnoPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoPilotoActionPerformed(evt);
            }
        });

        grupoRolPiloto.add(pReserva);
        pReserva.setForeground(new java.awt.Color(51, 51, 51));
        pReserva.setText("Reserva");

        grupoRolPiloto.add(pTitular);
        pTitular.setForeground(new java.awt.Color(51, 51, 51));
        pTitular.setText("Titular");
        pTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTitularActionPerformed(evt);
            }
        });

        grupoRolPiloto.add(pProbador);
        pProbador.setForeground(new java.awt.Color(51, 51, 51));
        pProbador.setText("Probador");
        pProbador.setToolTipText("");

        javax.swing.GroupLayout panelCargarPilotoLayout = new javax.swing.GroupLayout(panelCargarPiloto);
        panelCargarPiloto.setLayout(panelCargarPilotoLayout);
        panelCargarPilotoLayout.setHorizontalGroup(
            panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(543, Short.MAX_VALUE))
                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNroAutoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoEquipoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoNacionalidadPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoDiaPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoMesPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoAnoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pReserva)
                                    .addComponent(pTitular)
                                    .addComponent(pProbador))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel12)
                            .addComponent(botonGuardarPiloto))
                        .addGap(143, 143, 143))))
        );
        panelCargarPilotoLayout.setVerticalGroup(
            panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(campoNacionalidadPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(campoDiaPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoMesPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoAnoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(campoNroAutoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(campoEquipoPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(pTitular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pReserva)
                        .addGap(7, 7, 7)
                        .addGroup(panelCargarPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonGuardarPiloto)
                            .addComponent(pProbador)))
                    .addGroup(panelCargarPilotoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jLabel3.setText("Menu de Inicio");

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel3)
                .addContainerGap(341, Short.MAX_VALUE))
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel3)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        panelPilotos.setBackground(new java.awt.Color(255, 255, 255));

        botonCargarPiloto.setBackground(new java.awt.Color(100, 100, 100));
        botonCargarPiloto.setForeground(new java.awt.Color(255, 255, 255));
        botonCargarPiloto.setText("Cargar piloto");
        botonCargarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarPilotoActionPerformed(evt);
            }
        });

        botonEliminarPiloto.setBackground(new java.awt.Color(100, 100, 100));
        botonEliminarPiloto.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarPiloto.setText("Eliminar piloto");
        botonEliminarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPilotoActionPerformed(evt);
            }
        });

        botonMostrarPilotos.setBackground(new java.awt.Color(100, 100, 100));
        botonMostrarPilotos.setForeground(new java.awt.Color(255, 255, 255));
        botonMostrarPilotos.setText("Mostrar pilotos");
        botonMostrarPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarPilotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPilotosLayout = new javax.swing.GroupLayout(panelPilotos);
        panelPilotos.setLayout(panelPilotosLayout);
        panelPilotosLayout.setHorizontalGroup(
            panelPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPilotosLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(botonCargarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(botonEliminarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(botonMostrarPilotos)
                .addGap(37, 37, 37))
        );
        panelPilotosLayout.setVerticalGroup(
            panelPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilotosLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addGroup(panelPilotosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminarPiloto)
                    .addComponent(botonCargarPiloto)
                    .addComponent(botonMostrarPilotos))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        botonCargarComisario.setBackground(new java.awt.Color(100, 100, 100));
        botonCargarComisario.setForeground(new java.awt.Color(255, 255, 255));
        botonCargarComisario.setText("Cargar comisario");
        botonCargarComisario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarComisarioActionPerformed(evt);
            }
        });

        botonEliminarComisario.setBackground(new java.awt.Color(100, 100, 100));
        botonEliminarComisario.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarComisario.setText("Eliminar Comisario");
        botonEliminarComisario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarComisarioActionPerformed(evt);
            }
        });

        botonMostrarComisario.setBackground(new java.awt.Color(100, 100, 100));
        botonMostrarComisario.setForeground(new java.awt.Color(255, 255, 255));
        botonMostrarComisario.setText("Mostrar comisarios");
        botonMostrarComisario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarComisarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelComisariosLayout = new javax.swing.GroupLayout(panelComisarios);
        panelComisarios.setLayout(panelComisariosLayout);
        panelComisariosLayout.setHorizontalGroup(
            panelComisariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComisariosLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelComisariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonMostrarComisario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarComisario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCargarComisario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        panelComisariosLayout.setVerticalGroup(
            panelComisariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComisariosLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(botonCargarComisario)
                .addGap(18, 18, 18)
                .addComponent(botonEliminarComisario)
                .addGap(18, 18, 18)
                .addComponent(botonMostrarComisario)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        botonMostrarEquipos.setBackground(new java.awt.Color(100, 100, 100));
        botonMostrarEquipos.setForeground(new java.awt.Color(255, 255, 255));
        botonMostrarEquipos.setText("Mostrar Equipos");
        botonMostrarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarEquiposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEquiposLayout = new javax.swing.GroupLayout(panelEquipos);
        panelEquipos.setLayout(panelEquiposLayout);
        panelEquiposLayout.setHorizontalGroup(
            panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquiposLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(botonMostrarEquipos)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        panelEquiposLayout.setVerticalGroup(
            panelEquiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEquiposLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(botonMostrarEquipos)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelPilotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(panelComisarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(panelEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(17, 17, 17)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCargarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPilotos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelComisarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(panelEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelContenedorLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(panelCargarPiloto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /*/
    esta parte es para que solo se pueda seleccionar un rol al cargar un piloto nuevo
    grupoRolPiloto.add(pTitular);
    grupoRolPiloto.add(pReserva);
    grupoRolPiloto.add(pProbador);
    */
    
    private void botonCargarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarPilotoActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelCargarPiloto);
        panelContenedor.repaint();
        panelContenedor.revalidate();
    }//GEN-LAST:event_botonCargarPilotoActionPerformed

    private void botonEliminarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarPilotoActionPerformed

    private void botonMostrarPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarPilotosActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_botonMostrarPilotosActionPerformed

    private void botonPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPilotosActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelPilotos);
        panelContenedor.repaint();
        panelContenedor.revalidate();
    }//GEN-LAST:event_botonPilotosActionPerformed

    private void botonComisariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComisariosActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelComisarios);
        panelContenedor.repaint();
        panelContenedor.revalidate();        
    }//GEN-LAST:event_botonComisariosActionPerformed

    private void botonEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEquiposActionPerformed
        // TODO add your handling code here:
        panelContenedor.removeAll();
        panelContenedor.add(panelEquipos);
        panelContenedor.repaint();
        panelContenedor.revalidate();        
    }//GEN-LAST:event_botonEquiposActionPerformed

    private void campoNacionalidadPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNacionalidadPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNacionalidadPilotoActionPerformed

    private void campoNroAutoPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNroAutoPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNroAutoPilotoActionPerformed

    private void botonGuardarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPilotoActionPerformed
        // TODO add your handling code here:
        grupoRolPiloto.add(pTitular);
        grupoRolPiloto.add(pReserva);
        grupoRolPiloto.add(pProbador);
        Piloto p = new Piloto();
        p.setNombre(campoNombrePiloto.getText());
        p.setApellido(campoApellidoPiloto.getText());
        Fecha fechaNac = new Fecha();
        fechaNac.setDia(Integer.parseInt(campoDiaPiloto.getText()));
        fechaNac.setMes(Integer.parseInt(campoMesPiloto.getText()));
        fechaNac.setAno(Integer.parseInt(campoAnoPiloto.getText()));
        p.setFechaDeNacimiento(fechaNac);
        p.setNumeroDeAuto(Integer.parseInt(campoNroAutoPiloto.getText()));
        p.setEquipo(campoEquipoPiloto.getSelectedItem().toString());
        p.setNacionalidad(campoNacionalidadPiloto.getSelectedItem().toString());
        
        String rol = "";
        if(pTitular.isSelected()) rol = "Titular";
        else if(pReserva.isSelected()) rol = "Reserva";
        else if(pProbador.isSelected()) rol = "Probador";
        p.setRol(rol);
        lista.addPiloto(p);
        System.out.println("Se agrego el piloto nashe");
        p.mostrarDatosPi();
    }//GEN-LAST:event_botonGuardarPilotoActionPerformed

    private void campoDiaPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDiaPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDiaPilotoActionPerformed

    private void campoMesPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMesPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMesPilotoActionPerformed

    private void campoAnoPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoPilotoActionPerformed

    private void botonMostrarComisarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarComisarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMostrarComisarioActionPerformed

    private void botonEliminarComisarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarComisarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarComisarioActionPerformed

    private void botonCargarComisarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarComisarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCargarComisarioActionPerformed

    private void botonMostrarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMostrarEquiposActionPerformed

    private void pTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pTitularActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazGrafica().setVisible(true));
    }
       

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarComisario;
    private javax.swing.JButton botonCargarPiloto;
    private javax.swing.JButton botonComisarios;
    private javax.swing.JButton botonEliminarComisario;
    private javax.swing.JButton botonEliminarPiloto;
    private javax.swing.JButton botonEquipos;
    private javax.swing.JButton botonGuardarPiloto;
    private javax.swing.JButton botonMostrarComisario;
    private javax.swing.JButton botonMostrarEquipos;
    private javax.swing.JButton botonMostrarPilotos;
    private javax.swing.JButton botonPilotos;
    private javax.swing.JTextField campoAnoPiloto;
    private javax.swing.JTextPane campoApellidoPiloto;
    private javax.swing.JTextField campoDiaPiloto;
    private javax.swing.JComboBox<String> campoEquipoPiloto;
    private javax.swing.JTextField campoMesPiloto;
    private javax.swing.JComboBox<String> campoNacionalidadPiloto;
    private javax.swing.JTextPane campoNombrePiloto;
    private javax.swing.JTextField campoNroAutoPiloto;
    private javax.swing.ButtonGroup grupoRolPiloto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton pProbador;
    private javax.swing.JRadioButton pReserva;
    private javax.swing.JRadioButton pTitular;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCargarPiloto;
    private javax.swing.JPanel panelComisarios;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelEquipos;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelPilotos;
    // End of variables declaration//GEN-END:variables
}
